### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by paroque28** [JosephTico/TEC-Digital-File-Exporter#3]
```bash
Descargando cursos de HUMANISTICA 1 2019...
Descargando archivos de ANALISIS CRITICO DE LA TEORIA DEL COMPLOT GLOBAL:¿VIVIENDO EN LA MATRIX? GR 1...
0.00iB [00:00, ?iB/s]Traceback (most recent call last):
  File "/code/app.py", line 245, in <module>
    cli_login()
  File "/code/app.py", line 230, in cli_login
    with zipfile.ZipFile(filename,"r") as zip_ref:
  File "/usr/local/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
545iB [00:00, 35.3kiB/s]
```

**Comment by paroque28** [comment]
Contenido del ZIP:
```bash
$ cat download/HUMANISTICA\ 1\ 2019/ANALISIS\ CRITICO\ DE\ LA\ TEORIA\ DEL\ COMPLOT\ GLOBAL:¿VIVIENDO\ EN\ LA\ MATRIX\?\ GR\ 1.zip 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML>
<HEAD>
<TITLE>Not Found</TITLE>
</HEAD>
<BODY>
<H2>Not Found</H2>
The requested URL was not found on this server.
<P ALIGN=RIGHT><SMALL><I>AOLserver/4.5.1 on http://localhost</I></SMALL></P>
                                                                                                                                                                                                                                                                                        
</BODY></HTML>

```

**Comment by JosephTico** [comment]
Interesante... Cuál es la URL que intenta descargar del TD? (Puede hacer print de la linea 212).

**Comment by paroque28** [comment]
Hay algo raro con el curso `ANALISIS CRITICO DE LA TEORIA DEL COMPLOT GLOBAL:¿VIVIENDO EN LA MATRIX? GR 1`, literal un complot...
Este es el url:
https://tecdigital.tec.ac.cr/dotlrn/classes/FH/FH0222/H-1-2019.CA.FH0222.1/file-storage/download-archive?object_id=65041430

**Comment by paroque28** [comment]
Ok ya entendi, el TecDigital esta roto...

`https://tecdigital.tec.ac.cr/dotlrn/classes/FH/FH0222/H-1-2019.CA.FH0222.1/file-storage/download-archive?object_id=65041430 `
redirecciona a:

`https://tecdigital.tec.ac.cr/dotlrn/classes/FH/FH0222/H-1-2019.CA.FH0222.1/file-storage/download-archive/65041430/Documentos%20de%20ANALISIS%20CRITICO%20DE%20LA%20TEORIA%20DEL%20COMPLOT%20GLOBAL_%C2%BFVIVIENDO%20EN%20LA%20MATRIX?%20GR%201.zip`

Pero el signo de pregunta `?` no es un caracter valido.
Tiene que ser reemplazado por `%3F`

Fuente: https://stackoverflow.com/a/24723214

**Comment by paroque28** [comment]
Lo solucione haciendo un retry y si no solo salto el curso:

```python
        for curso in semestre["cursos"]:
            for attempt in range(5):
                try:
                    print("Descargando archivos de " + curso["titulo"] + "...")

                    url = curso["url"] + "/download-archive?object_id=" + curso["folder_id"]
                    print(url)
                    response = session.get(url, stream=True)
                    total_size_in_bytes= int(response.headers.get('content-length', 0))
                    block_size = 1024 #1 Kibibyte
                    progress_bar = tqdm(total=total_size_in_bytes, unit='iB', unit_scale=True)
                    filename = os.path.join(dirname, semestre["titulo"], curso["titulo"] + ".zip")
                    with open(filename, 'wb') as file:
                        for data in response.iter_content(block_size):
                            progress_bar.update(len(data))
                            file.write(data)
                    print(response)
                    if total_size_in_bytes != 0 and progress_bar.n != total_size_in_bytes:
                        raise Exception('Error al descargar el archivo.')

                    with zipfile.ZipFile(filename,"r") as zip_ref:
                        zip_ref.extractall(os.path.join(dirname, semestre["titulo"]))

                    os.remove(filename)

                    progress_bar.close()
                except KeyboardInterrupt:
                    sys.exit()
                except:
                    print("\n\nERROR: Error al descargar el archivo. \nReintentando...") 
                else:
                    break
            else:
                print("Ha ocurrido un error al descargar el curso " + curso["titulo"] + ".\nSaltando...")
            
```

**Comment by JosephTico** [comment]
> Ok ya entendi, el TecDigital esta roto..

Definitivamente, en muchos aspectos :P
